services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    links:
      - postgresql

  postgresql:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=godmother
      - POSTGRES_PASSWORD=g0dmother
      - POSTGRES_NAME=godmother_production
      - POSTGRES_EXTENSION=pg_trgm,btree_gist
  
volumes:
  postgresql-data:
