services:
  web:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    links:
      - postgresql
  postgresql:
    image: "postgres:latest"
    container_name: postgres
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-godmother}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-g0dmother}
      - POSTGRES_DB=${POSTGRES_DB:-dev_godmother}
      - POSTGRES_EXTENSION=pg_trgm,btree_gist
  mail:
    image: "mailhog/mailhog"
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  postgresql-data:
