secret_key_base: "dummy"
registration_types: ["mentee", "mentor"]
default_from: "godmother@example.com"
list_address: "godmother@example.com"
app_url: "http://localhost:3000"
db_name: "prod_godmother"
db_host: "postgresql"
db_port: "5432"
db_username: "godmother"
db_password: "g0dmother"    
smtp_settings:
  address: "mail"
  port: "1025"
  domain: ""
  user_name: ""
  password: ""
  authentication: "plain"
  enable_starttls_auto: true
