default: &default
  adapter: postgresql
  encoding: unicode
  host: "<%= Rails.application.config.x.db_host %>"
  port: "<%= Rails.application.config.x.db_port %>"
  username: "<%= Rails.application.config.x.db_username %>"
  password: "<%= Rails.application.config.x.db_password %>"

development:
  <<: *default
  database: godmother_development

test:
  <<: *default
  database: godmother_test

production:
  <<: *default
  database: "<%= Rails.application.config.x.db_name %>"
