default: &default
  adapter: postgresql
  encoding: unicode
  database: "<%= Rails.application.config.x.db_name %>"
  host: "<%= Rails.application.config.x.db_host %>"
  port: "<%= Rails.application.config.x.db_port %>"
  username: "<%= Rails.application.config.x.db_username %>"
  password: "<%= Rails.application.config.x.db_password %>"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
