---
- name: Install Nginx and Certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
      - apache2-utils # for htpasswd
    state: present
    update_cache: yes
  become: yes

- name: Remove default Nginx site configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: yes

- name: Set ssl_enabled to false
  set_fact:
    ssl_enabled: false

- name: Create Nginx site configuration without SSL
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/app
  become: yes

- name: Enable Nginx site configuration
  file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    state: link
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes

- name: Obtain SSL certificate
  command: certbot --nginx -d {{ domain }} --non-interactive --agree-tos --email {{ validation_mail }}
  become: yes
  register: certbot_result

- name: Set ssl_enabled to true if certbot succeeded
  set_fact:
    ssl_enabled: true
  when: certbot_result.rc == 0

- name: Create Nginx site configuration with SSL
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/app
  become: yes
  when: ssl_enabled | default(false)

- name: Create htpasswd file for basic auth
  command: htpasswd -bc /etc/nginx/.htpasswd {{ basic_auth_user }} {{ basic_auth_password }}
  when: basic_auth_enabled | default(false)
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes